### ISSUE TITLE
Change thumb photo resize spec

### ISSUE THREAD

**Issue by gbasilisco** [Ardakilic/WhatTheTag#40]
Hi, where can I set the size (actual I see 300x400) of thumb photo after upload?

Berst regards.

**Comment by Ardakilic** [comment]
Hello,

You can find the sizes here:

https://github.com/Ardakilic/WhatTheTag/blob/master/resources/views/photos/list.blade.php#L36

And here:

https://github.com/Ardakilic/WhatTheTag/blob/master/app/Photo.php#L67

**Comment by gbasilisco** [comment]
Hi, thanks for reply. But I mean a different question. I try to explain better. When I upload the photo, the system creates a thumb on file system. Where I can set spec of the thumb created on file system? Eg change the filename with append 400x300 text but I don’t se where this happen. Best regards.

**Comment by Ardakilic** [comment]
@gbasilisco The photo library Croppa generates the thumbnails dynamnically depending on the method called. If it's not found on the file system generates and then it caches, if found, it sources the generated one.

Try with original dimensions, then try chaning the sizes and see the generated sizes, you'll see what I mean.

try also changing the dimensions on the image source dynamically, you'll see it'll be generated almost magically :)

This way, it'll be easier to replace images depending on the altered design.

**Comment by gbasilisco** [comment]
@Ardakilic than is Croppa library that create the thumb. Do you know if there is a way to set thumb size? I see that the image i too bigger, on the FS the thumb is cropped. So best regards.

**Comment by Ardakilic** [comment]
@gbasilisco when you call it with the sizes parameters, it generates the thumbnail on the fly and stores on the file system. See the links I've provided earlier. Try changing them and it'll update for both old and new uploads.

**Comment by gbasilisco** [comment]
@Ardakilic ok, many thanks...Now I found the code that you indicate to me. best regards.
